version: 2
updates:
  - package-ecosystem: bundler
    directory: /docs
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: /kt
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: /py
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /rs
    schedule:
      interval: daily
