name:                aoc2020
version:             0.1.0.0
github:              "ephemient/aoc2020"
license:             BSD3
author:              "Daniel Lin"
maintainer:          "ephemient@gmail.com"
copyright:           "2020 Daniel Lin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ephemient/aoc2020/blob/main/hs/README.md>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - array
  - containers
  - deepseq
  - megaparsec
  - mtl
  - parser-combinators
  - split
  - text
  - unordered-containers
  - vector

executables:
  aoc2020-exe:
    main:                Main.lhs
    other-modules:
    - Paths_aoc2020
    source-dirs:         app
    c-sources:           app/cbits/main.c
    ghc-options:
    - -no-hs-main
    - -threaded
    - -pgmL markdown-unlit
    dependencies:
    - aoc2020
    - markdown-unlit
    - megaparsec
    - text

data-files:
- day*.txt

tests:
  aoc2020-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N -qg"'
    dependencies:
    - QuickCheck
    - aoc2020
    - containers
    - hspec
    - text

benchmarks:
  aoc2020-bench:
    main:                Main.hs
    source-dirs:         bench
    c-sources:           bench/cbits/main.c
    ghc-options:
    - -no-hs-main
    - -threaded
    dependencies:
    - aoc2020
    - criterion
    - text
